# Use the color palette
palette = "dracula"

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$fill\
$time\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$netns\
$shell\
$character"""

add_newline = true

[bun]
format = "via [$symbol]($style)"

[buf]
format = "via [$symbol]($style)"
symbol = " "

[cmake]
format = "via [$symbol]($style)"

[cobol]
format = "via [$symbol]($style)"

[crystal]
format = "via [$symbol]($style)"

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"
symbol = " "

[deno]
format = "via [$symbol]($style)"

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
format = 'via [$symbol]($style)'
symbol = " "

[elm]
format = 'via [$symbol]($style)'
symbol = " "

[erlang]
format = 'via [$symbol]($style)'

[fennel]
format = 'via [$symbol]($style)'

[golang]
format = 'via [$symbol]($style)'
symbol = " "

[gradle]
format = 'via [$symbol]($style)'

[haxe]
format = 'via [$symbol]($style)'
symbol = "⌘ "

[helm]
format = 'via [$symbol]($style)'

[julia]
format = 'via [$symbol]($style)'
symbol = " "

[kotlin]
format = 'via [$symbol]($style)'

[lua]
format = 'via [$symbol]($style)'
symbol = " "

[meson]
format = 'via [$symbol]($style)'
symbol = "喝 "

[nim]
format = 'via [$symbol]($style)'
symbol = " "

[nodejs]
symbol = " "
format = 'via [$symbol]($style)'

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
format = 'via [$symbol]($style)'

[perl]
format = 'via [$symbol]($style)'

[php]
format = 'via [$symbol]($style)'

[pulumi]
format = 'via [$symbol$stack]($style)'

[purescript]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'
symbol = " "

[raku]
format = 'via [$symbol]($style)'

[red]
format = 'via [$symbol]($style)'

[rlang]
format = 'via [$symbol]($style)'
symbol = "ﳒ "

[ruby]
format = 'via [$symbol]($style)'
symbol = " "

[rust]
format = 'via [$symbol]($style)'
symbol = " "

[swift]
format = 'via [$symbol]($style)'

[vagrant]
format = 'via [$symbol]($style)'

[vlang]
format = 'via [$symbol]($style)'

[zig]
format = 'via [$symbol]($style)'

[aws]
symbol = "  "

[c]
symbol = " "
format = 'via [$symbol]($style)'

[conda]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[pijul_channel]
symbol = "🪺 "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[time]
disabled = false
format = '[$time](bold)($style)'
time_format = '%a, %Y-%b-%d %H:%M:%S %Z'

[fill]
symbol = ' '

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
