FROM quay.io/fedora/fedora-toolbox:rawhide

RUN dnf install -y \
  ImageMagick \
  alacritty \
  kitty \
  bash-completion \
  fastfetch \
  git \
  neovim \
  ripgrep \
  vim-minimal \
  nix-core \
  which 
RUN dnf install -y\
  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
CMD ["/bin/bash"]
