
unbind r
bind r source-file ~/.tmux.conf

set-option -sg escape-time 10
set-option -sg focus-events on
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-overrides ",xterm-256color:Tc"

set -g base-index 1
setw -g pane-base-index 1

set-option -g prefix2 C-space
bind-key C-s send-prefix -2

set-window-option -g mode-keys vi

set -gq allow-passthrough on
set -g visual-activity off
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key x kill-pane
set -g detach-on-destroy off

set -g @plugin 'tmux-plugin/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator' 
set -g @plugin 'dracula/tmux'

set -g @dracula-plugins "git time"
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-refresh-rate 5
set -g @dracula-day-month true
set -g @dracula-military-time true

set -g @plugin 'alexwforsythe/tmux-which-key'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-boot 'on'
set -g @continuum-restore 'off'

set -g @plugin 'omerxx/tmux-floax'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run '~/.tmux/plugins/tpm/tpm'
